FROM ubuntu
ARG ARCH=${ARCH}

RUN apt-get update &&\
    apt-get install -y python3 &&\
    apt-get install -y vim

COPY build/bin/cvmart-log-pilot-linux-${ARCH} /pilot/pilot
COPY filebeat-binary/filebeat-linux-${ARCH} /usr/bin/filebeat
COPY assets/entrypoint assets/filebeat/ assets/healthz /pilot/

RUN chmod +x /pilot/pilot /pilot/entrypoint /pilot/healthz /pilot/config.filebeat

HEALTHCHECK CMD /pilot/healthz

WORKDIR /pilot/
ENV PILOT_TYPE=filebeat
ENTRYPOINT ["python3","/pilot/entrypoint"]
