apiVersion: apps/v1
kind: DaemonSet
metadata:
  name:  cvmart-daemon
  labels:
    name: cvmart-daemon
    app: cvmart-daemon
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: cvmart-daemon
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 4
  template:
    metadata:
      labels:
        name: cvmart-daemon
        app: cvmart-daemon
    spec:
      serviceAccount: pod-reader-account
      containers:
        - image: 192.168.1.76:8099/evtrain/cvmart-daemon:v1.0
          imagePullPolicy: Always
          name: log-pilot
          securityContext:
            privileged: true
          args:
            - "-base=/host"
          resources:
            requests:
              cpu: "20m"
              memory: "200M"
          livenessProbe:
            exec:
              command: ["/bin/bash","-c","/pilot/healthz"]
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:  ["/bin/bash","-c","/pilot/healthz"]
            initialDelaySeconds: 5
            timeoutSeconds: 5
          ports:
            - containerPort:  5465
              name:  daemon
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
            - mountPath: /host
              name: host
              readOnly: true
            - mountPath: /out
              name: filebeat-out
            - mountPath: /config
              name: filebeat-config
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /etc/cvmart/
              name: daemon-config
              readOnly: true
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: host
          hostPath:
            path: /
        - name: filebeat-out
          hostPath:
            path: /log-monitor/out
        - name: filebeat-config
          hostPath:
            path: /log-monitor/config
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: daemon-config
          configMap:
            name: cvmart-daemon-cm
            items:
              - key: daemon-config.json
                path: daemon-config.json
      restartPolicy: Always
      imagePullSecrets:
        - name: "eagle-nest-registry-key"
      # nodeSelector:
      #   kubernetes.io/arch: amd64
---
kind: Service
apiVersion: v1
metadata:
  name: cvmart-daemon-service
  namespace: kube-system
spec:
  selector:
    app: cvmart-daemon
  type: NodePort
  ports:
    - name: daemon
      port: 5645
      targetPort: 5645
      nodePort: 5645



---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cvmart-daemon-cm
  namespace: kube-system
data:
  daemon-config.json: |
    {
      "server_port": 5645,
      "secret_key": "123",
      "docker_server_port": 2375,
      "docker_auth": {
        "user_name": "",
        "pass_word": "",
        "token": ""
      },
      "kube_api_url":"http://192.168.1.131:6443",
      "kube_auth": {
        "user_name": "",
        "pass_word": "",
        "token": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ii1EQkxmRVlFMnFBNm1xcHk3U2NhSm0xUGhaZnlsT2dZeFNIZUFRZzBLU0UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi14bjh0cCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjYyOTQ0YmQwLTNhN2MtNDNlYy05MTYyLTc3ZGNjYTEwMDU3NyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.JCyjrKbVMVis28DIAjp1L9BwlqT3XXGrTHH_oUN_4Xu6gcOP2GOokg9S66CXZR7CSPTtTWbpRFHu3KyoISQFl5TxatDGrHvEjbMtcugwHBTW6yrfxJs_woN4QphlFq5wBzmwcpvC1MXuj3VTIRvabnivfL3wa2qw3iccP8eYSPpaySVKChu60WW_oYMrvVOL3PG01DlWY2PuVS6-uHliCal5_lY22VWKo8AROpoe8tWVa5YEeY45LEe9bsK-WXqY9OweN3PLOGELpjAeY5wc5GJCsACm9Jvv43CfuGopz7rKD005dlfojY4GvF9IVnEMSXFtv0ZtDRSMwPqECubsnQ"
      },
      "remote_proxy_host": "",
      "enable_proxy": false,
      "bucket": "cvmart-log",
      "minio_url": "192.168.1.175:9000",
      "minio_auth": {
        "user_name": "admin",
        "pass_word": "admin123",
        "token": ""
      },
      "pilot_type": "filebeat",
      "pilot_log_prefix": "cvmart"
    }


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  pod-reader-account
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-global
subjects:
  - kind: ServiceAccount
    name: pod-reader-account
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io
